"apiVersion": "operator.openshift.io/v1"
"kind": "IngressController"
"metadata":
  "annotations":
    "Owner": "cluster-ingress-operator"
    "ingress.operator.openshift.io/auto-delete-load-balancer": "true"
  "creationTimestamp": "2024-05-03T17:33:05Z"
  "finalizers":
  - "ingresscontroller.operator.openshift.io/finalizer-ingresscontroller"
  "generation": 5
  "managedFields":
  - "apiVersion": "operator.openshift.io/v1"
    "fieldsType": "FieldsV1"
    "fieldsV1":
      "f:metadata":
        "f:finalizers":
          ".": {}
          "v:\"ingresscontroller.operator.openshift.io/finalizer-ingresscontroller\"": {}
      "f:spec":
        ".": {}
        "f:clientTLS":
          ".": {}
          "f:clientCA":
            ".": {}
            "f:name": {}
          "f:clientCertificatePolicy": {}
        "f:endpointPublishingStrategy":
          ".": {}
          "f:loadBalancer":
            ".": {}
            "f:dnsManagementPolicy": {}
            "f:providerParameters":
              ".": {}
              "f:aws":
                ".": {}
                "f:type": {}
              "f:type": {}
            "f:scope": {}
          "f:type": {}
        "f:httpCompression": {}
        "f:httpEmptyRequestsPolicy": {}
        "f:httpErrorCodePages":
          ".": {}
          "f:name": {}
        "f:replicas": {}
        "f:tuningOptions":
          ".": {}
          "f:reloadInterval": {}
        "f:unsupportedConfigOverrides": {}
    "manager": "ingress-operator"
    "operation": "Update"
    "time": "2024-05-03T17:33:05Z"
  - "apiVersion": "operator.openshift.io/v1"
    "fieldsType": "FieldsV1"
    "fieldsV1":
      "f:metadata":
        "f:annotations":
          ".": {}
          "f:Owner": {}
          "f:ingress.operator.openshift.io/auto-delete-load-balancer": {}
      "f:spec":
        "f:defaultCertificate": {}
        "f:domain": {}
        "f:namespaceSelector": {}
        "f:nodePlacement":
          ".": {}
          "f:nodeSelector": {}
          "f:tolerations": {}
        "f:routeAdmission":
          ".": {}
          "f:namespaceOwnership": {}
          "f:wildcardPolicy": {}
        "f:routeSelector": {}
    "manager": "manager"
    "operation": "Update"
    "time": "2024-05-03T20:02:56Z"
  - "apiVersion": "operator.openshift.io/v1"
    "fieldsType": "FieldsV1"
    "fieldsV1":
      "f:status":
        ".": {}
        "f:availableReplicas": {}
        "f:conditions": {}
        "f:domain": {}
        "f:endpointPublishingStrategy":
          ".": {}
          "f:loadBalancer":
            ".": {}
            "f:dnsManagementPolicy": {}
            "f:providerParameters":
              ".": {}
              "f:aws":
                ".": {}
                "f:type": {}
              "f:type": {}
            "f:scope": {}
          "f:type": {}
        "f:namespaceSelector": {}
        "f:observedGeneration": {}
        "f:routeSelector": {}
        "f:selector": {}
        "f:tlsProfile":
          ".": {}
          "f:ciphers": {}
          "f:minTLSVersion": {}
    "manager": "ingress-operator"
    "operation": "Update"
    "subresource": "status"
    "time": "2024-05-03T20:03:29Z"
  "name": "default"
  "namespace": "openshift-ingress-operator"
  "resourceVersion": "192859"
  "uid": "b0302420-b2f5-4e9c-a01d-362520c26ca5"
"spec":
  "clientTLS":
    "allowedSubjectPatterns": null
    "clientCA":
      "name": ""
    "clientCertificatePolicy": ""
  "defaultCertificate":
    "name": "classic-102-primary-cert-bundle-secret"
  "domain": "apps.classic-102.swew.p1.openshiftapps.com"
  "endpointPublishingStrategy":
    "hostNetwork":
      "httpPort": null
      "httpsPort": null
      "protocol": null
      "statsPort": null
    "loadBalancer":
      "allowedSourceRanges": null
      "dnsManagementPolicy": "Managed"
      "providerParameters":
        "aws":
          "classicLoadBalancer":
            "connectionIdleTimeout": null
          "networkLoadBalancer": null
          "type": "NLB"
        "gcp":
          "clientAccess": null
        "ibm":
          "protocol": null
        "type": "AWS"
      "scope": "External"
    "nodePort":
      "protocol": null
    "private":
      "protocol": null
    "type": "LoadBalancerService"
  "httpCompression":
    "mimeTypes": null
  "httpEmptyRequestsPolicy": "Respond"
  "httpErrorCodePages":
    "name": ""
  "httpHeaders":
    "actions":
      "request": null
      "response": null
    "forwardedHeaderPolicy": null
    "headerNameCaseAdjustments": null
    "uniqueId":
      "format": null
      "name": null
  "logging":
    "access":
      "destination":
        "container":
          "maxLength": null
        "syslog":
          "address": null
          "facility": null
          "maxLength": null
          "port": null
        "type": null
      "httpCaptureCookies": null
      "httpCaptureHeaders":
        "request": null
        "response": null
      "httpLogFormat": null
      "logEmptyRequests": null
  "namespaceSelector":
    "matchExpressions": []
    "matchLabels": null
  "nodePlacement":
    "nodeSelector":
      "matchExpressions": null
      "matchLabels":
        "node-role.kubernetes.io/infra": ""
    "tolerations":
    - "effect": "NoSchedule"
      "key": "node-role.kubernetes.io/infra"
      "operator": "Exists"
      "tolerationSeconds": null
      "value": null
  "replicas": 2
  "routeAdmission":
    "namespaceOwnership": "Strict"
    "wildcardPolicy": "WildcardsDisallowed"
  "routeSelector":
    "matchExpressions": []
    "matchLabels": null
  "tlsSecurityProfile":
    "custom":
      "ciphers": null
      "minTLSVersion": null
    "intermediate": null
    "modern": null
    "old": null
    "type": null
  "tuningOptions":
    "clientFinTimeout": null
    "clientTimeout": null
    "headerBufferBytes": null
    "headerBufferMaxRewriteBytes": null
    "healthCheckInterval": null
    "maxConnections": null
    "reloadInterval": "0s"
    "serverFinTimeout": null
    "serverTimeout": null
    "threadCount": null
    "tlsInspectDelay": null
    "tunnelTimeout": null
  "unsupportedConfigOverrides": null
"status":
  "availableReplicas": 2
  "conditions":
  - "lastTransitionTime": "2024-05-03T17:33:05Z"
    "message": null
    "reason": "Valid"
    "status": "True"
    "type": "Admitted"
  - "lastTransitionTime": "2024-05-03T17:39:47Z"
    "message": "The deployment has Available status condition set to True"
    "reason": "DeploymentAvailable"
    "status": "True"
    "type": "DeploymentAvailable"
  - "lastTransitionTime": "2024-05-03T17:39:47Z"
    "message": "Minimum replicas requirement is met"
    "reason": "DeploymentMinimumReplicasMet"
    "status": "True"
    "type": "DeploymentReplicasMinAvailable"
  - "lastTransitionTime": "2024-05-03T20:03:29Z"
    "message": "All replicas are available"
    "reason": "DeploymentReplicasAvailable"
    "status": "True"
    "type": "DeploymentReplicasAllAvailable"
  - "lastTransitionTime": "2024-05-03T20:03:29Z"
    "message": "Deployment is not actively rolling out"
    "reason": "DeploymentNotRollingOut"
    "status": "False"
    "type": "DeploymentRollingOut"
  - "lastTransitionTime": "2024-05-03T17:33:06Z"
    "message": "The endpoint publishing strategy supports a managed load balancer"
    "reason": "WantedByEndpointPublishingStrategy"
    "status": "True"
    "type": "LoadBalancerManaged"
  - "lastTransitionTime": "2024-05-03T17:33:09Z"
    "message": "The LoadBalancer service is provisioned"
    "reason": "LoadBalancerProvisioned"
    "status": "True"
    "type": "LoadBalancerReady"
  - "lastTransitionTime": "2024-05-03T17:33:06Z"
    "message": "LoadBalancer is not progressing"
    "reason": "LoadBalancerNotProgressing"
    "status": "False"
    "type": "LoadBalancerProgressing"
  - "lastTransitionTime": "2024-05-03T17:33:06Z"
    "message": "DNS management is supported and zones are specified in the cluster
      DNS config."
    "reason": "Normal"
    "status": "True"
    "type": "DNSManaged"
  - "lastTransitionTime": "2024-05-03T17:33:28Z"
    "message": "The record is provisioned in all reported zones."
    "reason": "NoFailedZones"
    "status": "True"
    "type": "DNSReady"
  - "lastTransitionTime": "2024-05-03T17:39:47Z"
    "message": null
    "reason": null
    "status": "True"
    "type": "Available"
  - "lastTransitionTime": "2024-05-03T20:03:29Z"
    "message": null
    "reason": null
    "status": "False"
    "type": "Progressing"
  - "lastTransitionTime": "2024-05-03T17:39:47Z"
    "message": null
    "reason": null
    "status": "False"
    "type": "Degraded"
  - "lastTransitionTime": "2024-05-03T17:33:06Z"
    "message": "IngressController is upgradeable."
    "reason": "Upgradeable"
    "status": "True"
    "type": "Upgradeable"
  - "lastTransitionTime": "2024-05-03T17:33:06Z"
    "message": "No evaluation condition is detected."
    "reason": "NoEvaluationCondition"
    "status": "False"
    "type": "EvaluationConditionsDetected"
  - "lastTransitionTime": "2024-05-03T17:40:53Z"
    "message": "Canary route checks for the default ingress controller are successful"
    "reason": "CanaryChecksSucceeding"
    "status": "True"
    "type": "CanaryChecksSucceeding"
  "domain": "apps.classic-102.swew.p1.openshiftapps.com"
  "endpointPublishingStrategy":
    "hostNetwork":
      "httpPort": null
      "httpsPort": null
      "protocol": null
      "statsPort": null
    "loadBalancer":
      "allowedSourceRanges": null
      "dnsManagementPolicy": "Managed"
      "providerParameters":
        "aws":
          "classicLoadBalancer":
            "connectionIdleTimeout": null
          "networkLoadBalancer": null
          "type": "NLB"
        "gcp":
          "clientAccess": null
        "ibm":
          "protocol": null
        "type": "AWS"
      "scope": "External"
    "nodePort":
      "protocol": null
    "private":
      "protocol": null
    "type": "LoadBalancerService"
  "namespaceSelector":
    "matchExpressions": null
    "matchLabels": null
  "observedGeneration": 5
  "routeSelector":
    "matchExpressions": null
    "matchLabels": null
  "selector": "ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default"
  "tlsProfile":
    "ciphers":
    - "ECDHE-ECDSA-AES128-GCM-SHA256"
    - "ECDHE-RSA-AES128-GCM-SHA256"
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES256-GCM-SHA384"
    - "ECDHE-ECDSA-CHACHA20-POLY1305"
    - "ECDHE-RSA-CHACHA20-POLY1305"
    - "DHE-RSA-AES128-GCM-SHA256"
    - "DHE-RSA-AES256-GCM-SHA384"
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    "minTLSVersion": "VersionTLS12"
